# Generated by Django 5.0.7 on 2024-08-24 09:23

import Management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_delete_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'ADMIN'), (1, 'EDITOR'), (2, 'VIEWER')], default=Management.models.Role['VIEWER']),
        ),
    ]
