# Generated by Django 5.0.7 on 2024-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_profile_permissions_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
