# Generated by Django 5.0.7 on 2024-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_remove_profile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
