# Generated by Django 5.0.7 on 2024-08-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picturte_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
