# Generated by Django 5.0.7 on 2024-08-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
        ('Origames', '0002_user_profile_picturte_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='Management.user'),
        ),
        migrations.AddField(
            model_name='runner',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(related_name='games', to='Management.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
