# Generated by Django 5.0.7 on 2024-08-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0003_alter_game_creator_runner_email_alter_game_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
        migrations.AddField(
            model_name='game',
            name='runners',
            field=models.ManyToManyField(related_name='games_as_runner', to='Origames.runner'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games_as_player', to='Origames.player'),
        ),
    ]
