# Generated by Django 5.0.7 on 2024-08-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0004_player_remove_game_users_game_runners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
