# Generated by Django 5.0.7 on 2024-08-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0005_runner_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
