# Generated by Django 5.0.7 on 2024-08-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0006_runner_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_coin',
            field=models.IntegerField(default=40),
        ),
    ]
