# Generated by Django 5.0.7 on 2024-08-23 21:45

import Origames.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0007_game_max_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='gender',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=Origames.models.Gender['MALE']),
        ),
    ]
