# Generated by Django 5.0.7 on 2024-08-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0008_runner_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
