# Generated by Django 5.0.7 on 2024-09-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0013_alter_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='time',
            field=models.DurationField(default=0),
        ),
    ]
