# Generated by Django 5.0.7 on 2024-09-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0014_alter_runner_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
