# Generated by Django 5.0.7 on 2024-09-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0015_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Origames.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Origames.player')),
                ('runnner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Origames.runner')),
            ],
        ),
    ]
