# Generated by Django 5.0.7 on 2024-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0016_remove_player_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='runners',
            field=models.ManyToManyField(blank=True, null=True, related_name='games_as_runner', to='Origames.runner'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='runnner',
        ),
        migrations.AddField(
            model_name='team',
            name='runnner',
            field=models.ManyToManyField(related_name='selections', to='Origames.runner'),
        ),
    ]
