# Generated by Django 5.0.7 on 2024-09-25 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0017_alter_game_runners_remove_team_runnner_team_runnner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='runners',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Origames.game'),
        ),
        migrations.AddField(
            model_name='runner',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Origames.game'),
        ),
    ]
