# Generated by Django 5.0.7 on 2024-09-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0018_remove_game_players_remove_game_runners_player_game_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'email')},
        ),
    ]
