# Generated by Django 5.0.7 on 2024-09-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0019_alter_player_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='runnner',
            field=models.ManyToManyField(blank=True, default=None, related_name='selections', to='Origames.runner'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
