# Generated by Django 5.0.7 on 2024-09-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0020_player_runnner_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='runnner',
            field=models.ManyToManyField(blank=True, default=None, related_name='runners', to='Origames.runner'),
        ),
    ]
