# Generated by Django 5.0.7 on 2024-09-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0022_rename_runnner_player_runnners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='runnners',
            field=models.ManyToManyField(blank=True, default=None, related_name='name_runner', to='Origames.runner'),
        ),
    ]
