# Generated by Django 5.0.7 on 2024-10-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Origames', '0023_alter_player_runnners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='athlete',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Origames.athlete'),
        ),
    ]
